### ISSUE TITLE
height of images in team section to be fixed

### ISSUE THREAD

**Issue by sudipt1999** [dscgeu/dscgeu.github.io#2]
On team section images are not of same height width! Kindly look forward to it !

**Comment by dimkov41** [comment]
How you run that projects when the version set to "q.0.0"?

**Comment by petr7555** [comment]
@sudipt1999 Hi, I have fixed this in https://github.com/dscgeu/dscgeu.github.io/pull/3. Please assign this to me and merge if you are content with the changes.

**Comment by sudipt1999** [comment]
@dimkov41 its a static website you can directly open .html files

**Comment by sudipt1999** [comment]
@petr7555  thanks for your pr ! I will surely merge once I confirm the changes!

**Comment by sudipt1999** [comment]
@petr7555 thanks for your work!
