### ISSUE TITLE
Chnage the script tag into a script.js file and link to all

### ISSUE THREAD

**Issue by amanjagdev** [dscgeu/dscgeu.github.io#5]
There is a script tag in index.html and possibly in other html pages present in pages folder copy that and make them into a script.js file put it in assets/js and link it to all html pages

**Comment by khusharth** [comment]
can i work on this?

**Comment by khusharth** [comment]
and can you guide me on how can i run this project locally?

**Comment by amanjagdev** [comment]
Just Clone the project and you can use any backend local server to run it best method would be:

1. Use live server extension if you use vscode as the ide
2. Use xampp or wamp like software to make local server

**Comment by khusharth** [comment]
#8 Added a pull request for it.

**Comment by amanjagdev** [comment]
resolved
